---
- hosts: kafkaserver
  become: true
  vars:
    ansible_dir: './../'
    dest_dir: '/tmp'
  roles:
    - ./../roles/docker
    - ./../roles/docker_containers
  tasks:
    - name: Copy kafka.properties
      copy:
        src: '{{ ansible_dir }}/kafka_server/{{ item }}'
        dest: '{{ dest_dir }}'
      with_items:
        - kafka.properties
        - docker-compose.yml
        - filebeat.docker.yml

    - name: Run docker compose
      shell: echo "Run docker compose"
      notify:
        - docker compose down
        - docker compose up
