- name: docker compose down
  vars:
    _dest_dir: /tmp
  shell: |
    docker compose -f {{dest_dir}}/docker-compose.yml down

- name: docker compose down env
  vars:
    _dest_dir: /tmp
  shell: |
    docker compose -f {{dest_dir}}/docker-compose.yml --env-file {{dest_dir}}/.env down

- name: set elastic search map count
  sysctl: name={{ item.key }} value={{ item.value }}
  with_items:
    - { key: 'vm.max_map_count', value: '262144' }

- name: docker compose up
  vars:
    _dest_dir: /tmp
  shell: |
    docker compose -f {{dest_dir}}/docker-compose.yml up -d

- name: docker compose up env
  vars:
    _dest_dir: /tmp
  shell: |
    docker compose -f {{dest_dir}}/docker-compose.yml --env-file {{dest_dir}}/.env up -d
