instances:
  - name: es01
    dns:
      - es01
      - localhost
    ip:
      - 127.0.0.1
      - 172.104.11.16
      - 192.168.1.123

  - name: es02
    dns:
      - es02
      - localhost
    ip:
      - 127.0.0.1
      - 172.104.11.16
      - 192.168.1.123

  - name: es03
    dns:
      - es03
      - localhost
    ip:
      - 127.0.0.1
      - 172.104.11.16
      - 192.168.1.123

  - name: filebeat
    dns:
      - filebeat
      - localhost
    ip:
      - 127.0.0.1
      - 45.79.175.237
      - 192.168.1.123
